{{- $certData := index $.Values.redisCert "redis" }}
{{- if or $certData.ca $certData.cert $certData.key }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-cmdb.fullname" $ }}-web-redis-certs
data:
  {{- if $certData.ca }}
  redis.ca: {{ $certData.ca | b64dec | quote }}
  {{- end }}
  {{- if $certData.cert }}
  redis.cert: {{ $certData.cert | b64dec | quote }}
  {{- end }}
  {{- if $certData.key }}
  redis.key: {{ $certData.key | b64dec | quote }}
  {{- end }}
{{- end }} 
